config/routes.rb
Rails.application.routes.draw do
  root to: 'application#welcome'
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks'}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :travels, only: [:new, :create, :index, :show] do
    resources :companies, only: [:new, :create, :index]
    resources :offers, only: [:new, :index, :create]
  end

  resources :offers, only: [:create, :index]
  resources :companies, only: [:new, :create, :index]

  get '/companies/:category', to: 'companies#category'
  get '/travels/:category', to: 'travels#category'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user, optional: true
  has_many :offers
  has_many :travels, through: :offers
  accepts_nested_attributes_for :offers
  validates_presence_of :name, :location

  scope :category, ->(category) {where(category: category)}
  
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :company, optional: true
  belongs_to :travel
  validates_presence_of :description
end

app/models/path.rb
class Path < ApplicationRecord
  has_many :users
  has_many :companies, through: :offers
end

app/models/travel.rb
class Travel < ApplicationRecord
  has_many :users
  has_many :offers
  has_many :companies, through: :offers
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

   has_many :offers
   has_many :companies
   accepts_nested_attributes_for :companies
   has_many :travels, through: :offers
   validates_presence_of :username, :password, :password_confirmation
   validates_uniqueness_of :username

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.username = auth.info.name
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.password_confirmation = Devise.friendly_token[0,20]
      user.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def require_login
    redirect_to root_path unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def log_in(user)
    session[:user_id] = user.id
  end

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController

  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :require_login, only: [:new, :create]
  before_action :get_current_companies, only: [:new, :create]

  def new
    get_current_travel
    current_user.companies.build
    @user = current_user
    @company = current_user.companies.new
    @travel = Travel.all
    @all_companies = Company.all
  end

  def index
    get_current_travel
    @user = current_user
    @companies = current_user.companies
    @company = current_user.companies.new
    @travel = Travel.all
    @all_companies = Company.all
  end

  def create
    @company = current_user.companies.new(company_params)
      if @company.save
        redirect_to companies_path
      else
        render :new
      end
  end

  def category
    @deals = Company.category(params[:category].capitalize)
  end

  private

  def company_params
    params.require(:company).permit(:company_id, :name, :location, :category, offers_attributes: [:description, :travel_id])
  end

  def get_current_travel
    @travel ||= Travel.find_by(id: params[:travel_id])
  end

  def get_current_companies
    @company ||=Company.find_by(id: params[:company_id])
  end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :require_login, only: [:new, :create]

  def new
    current_user.companies.build
    @user = current_user
    @companies = current_user.companies
    @company = current_user.companies.new
    @travel = Travel.all
    @all_companies = Company.all
    # find_travel
  end

  def index
      if user_signed_in?
        @offers = current_user.companies
        current_user_offers
        # user_route_offers
      else
        @offers = Offer.all
      end
  end

  def create
    @offer = Offer.new(offer_params)
      if @offer.save
        redirect_to travel_path(@offer.travel.id)
      else
        set_travel
        @offer.errors.full_messages
        redirect_to new_travel_offer_path(@travel)
      end
  end

  def show
    @offer = Offer.find(params[:id])
  end

  private

  def offer_params
    params.require(:offer).permit(:description, :travel_id, company_attributes: [:name, :location, :category])
  end

  # def find_travel
  #   @travel = Travel.find(params[:travel_id])
  # end

  def set_travel
    @travel = Travel.find(params[:offer][:travel_id])
  end

  def current_user_offers
    current_user.companies.each do |user_offers|
      user_offers.offers
    end
  end

  # def user_route_offers
  #   @a = []
  #   current_user.companies.select(:id).each do |uuu|
  #     @a << find_travel.offers.select {|o| o.company_id == uuu.id}
  #   end
  #   @a
  # end



end

app/controllers/paths_controller.rb
class PathsController < ApplicationController

  def new
  end

  def index
  end

  def create
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      log_in(@user)
      redirect_to travels_path
    else
      @error = "Please try again"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to travels_path
  end

end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :require_login, only: [:new, :create]
  before_action :get_travel_route, only: [:new, :index]

  def new
    @travel = Travel.new
  end

  def index
      @travels = Travel.all
  end

  def create
    @travel = Travel.new(travel_params)
      if @travel.save
        redirect_to travels_path
      else
        render :new
      end
  end


  def category
    @deals = Company.category(params[:category].capitalize)
  end

  def show
    get_travel_route ? (get_travel_route) : (redirect_to root_path)
  end

  # def all
  #   @offers = Offers.all
  # end

  private

  def travel_params
    params.require(:travel).permit(:name)
  end

  def get_travel_route
    @travel ||= Travel.find_by(id: params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @user.companies.build.offers.build
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to travels_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :companies_attributes => [:name, :location, :category], :offers_attributes => [:description])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def admin
    current_user.username == "admin"
  end

  def admin_email
    current_user.email == "ku7%4ffth%43@oPmn"
  end

  def current_user_offers
    Company.find_by(user_id: current_user.id).offers
  end
  
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/offer_helper.rb
module OfferHelper
end

app/helpers/path_helper.rb
module PathHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/application/welcome.html.erb
<h1 class="logo"> QPons </h1>
<div class="home-container">
<h2>Click the link below to check out the great offers!</h2>
    <% if user_signed_in? %>
<h3><%= link_to 'View your current offers', companies_path %></h3>
<h3><%= link_to 'Add a new offer', new_company_path %></h3>

<% end %>
<h3><%= link_to 'View all current offers', travels_path %></h3><br>

<% if user_signed_in? && admin %>
  <h3><%= link_to 'Add a new travel', new_travel_path %></h3>
<% end %>

<h4>Future features for this whitespace: Offer of the day, Top offers, New companies promo, Other ad/promo</h4>
</div>

app/views/companies/category.html.erb
<div class="company-list">
<h2> List of companies with <%=params[:category].capitalize%> offers </h2>

  <h3><%= link_to 'View all current offers', travels_path %></h3>

  <h2>Offers</h2>
  <%@deals.each.with_index(1) do |deal, index|%>
    <p><%=index%>.</p>
      <p>Name: <%=deal.name%></p>
      <p>Location: <%=deal.location%></p>

      <p><%deal.offers.each do |offer|%></p>
        <p>Offer: <%=offer.description%></p>
        <% end %>
  <% end %>
  </div>

app/views/companies/index.html.erb
<div class="company-list">
<h2> List of all your companies </h2>

<h3>
<p><%=link_to "All", companies_path %></p>
<p><%=link_to "Food", {:controller => "companies", :action => "category", :category => "food" }%></p>
<p><%=link_to "Technology", {:controller => "companies", :action => "category", :category => "technology" }%></p>
<p><%=link_to "Clothing", {:controller => "companies", :action => "category", :category => "clothing" }%></p>
<p><%=link_to "Footwear", {:controller => "companies", :action => "category", :category => "footwear" }%></p>
<p><%=link_to "Auto", {:controller => "companies", :action => "category", :category => "auto" }%></p>
<p><%=link_to "Drugstore", {:controller => "companies", :action => "category", :category => "drugstore" }%></p><br><br>
<!-- #link_to "Add a new company and offer", new_company_path <br><br>-->
<%= link_to 'View all current offers', travels_path %></h3>

<% if user_signed_in? %>
  <br><br><%= link_to "Add a new company and offer", new_company_path %>
<% end %>


<%@companies.each.with_index(1) do |comp, index|%>
    <h2><%=index%></h2>
  <h2><%="Name: #{comp.name}"%></h2>
  <h3><%="Location: #{comp.location}"%></h3>

  <p><%comp.offers.each do |offer|%></p>
    <h3><%="Offer: #{offer.description}"%></h3>
     <% end %>
<% end %>
</div>

app/views/companies/new.html.erb
<div class="new-company">
<h2> Enter a new company and offer </h2>

<div class="field_with_errors">
  <%= render partial: '/errors', locals: { record: @company } %>
</div>


<%= form_for @company do |s| %>
  <div class="form-group">
    <p><%= s.label :Company_name %>
    <%= s.text_field :name %></p>
    <p><%= s.label :location %>
    <%= s.text_field :location %></p>
    <p><%= s.label :category %>
    <%= s.text_field :category %></p>
  <!--#s.collection_select :companies, :category, @all_companies, :id, :category //-->
  </div><br>

  <%= s.fields_for :offers, Offer.new do |e| %>
  <div class="form-group">
    <p><%= e.label :route %>
    <%= e.collection_select :travel_id, Travel.all, :id, :name %></p>
    <p><%= e.label :offer_description %>
    <%= e.text_field :description%></p>
    </div><br>
<% end %>
<div class="submit-button"><%= s.submit %></div>
<% end %>
</div>

app/views/offers/index.html.erb
<div class="current-offers">
  <h2> All current offers </h2>


  <h3> <%= link_to "View offers by route or category", travels_path %> </h3>

  <% @offers.each.with_index(1) do |comp, index| %>
  <h3><%=index%></h3>
  <h3><%="Company: #{comp.name}" %></h3>
  <h3><%="Category: #{comp.category}" %></h3>
  <h3><%="Location: #{comp.location}" %></h3>

    <% comp.offers.each do |offer| %>
      <p><%="Description: #{offer.description}" %></p>
  <% end %>

  <% end %>
  </div>

app/views/offers/new.html.erb
<div class="new-offer">
<h2> Enter a new offer on Route <%= @travel.name %> </h2>

<div class="field_with_errors">
  <%= render partial: '/errors', locals: { record: @company } %>
</div>
<%= form_for @company do |s| %>
  <div class="form-group">
    <%= s.label :Company_name %>
    <%= s.text_field :name %>
    <%= s.label :location %>
    <%= s.text_field :location %>
    <%= s.label :category %>
    <%= s.text_field :category %>
  </div><br>

  <%= s.fields_for :offers, Offer.new do |e| %>
  <div class="form-group">
    <%= e.label :offer_description %>
    <%= e.text_field :description%>
    <%= e.hidden_field :travel_id, value: @travel %>
    </div><br>
<% end %>
<%= s.submit %>
<% end %>
</div>

app/views/travels/all.html.erb
<div class="current-offers">
<% @offers.each.with_index(1) do |offer, index| %>
<h3><%=index%></h3>
<h3>Company: <%= offer.company.name %></h3>
<h3>Category: <%= offer.company.category %></h3>
<h3>Location: <%= offer.company.location %></h3>
<p>Description: <%= offer.description %></p>
<% end %>
</div>

app/views/travels/category.html.erb
<div class="company-list">
<h2> List of companies with <%=params[:category].capitalize%> offers </h2>

  <h3><%= link_to 'View all current offers', travels_path %></h3>

  <%@deals.each.with_index(1) do |deal, index|%>
    <p><%=index%>
      <p>Name: <%=deal.name%></p>
      <p>Location: <%=deal.location%></p>

      <p><%deal.offers.each do |offer|%></p>
        <p>Offer: <%=offer.description%></p>
        <% end %>
  <% end %>
  </div>

app/views/travels/index.html.erb
<div class="current-offers">
<h2> Choose a route to see current offers </h2>

  <%@travels.each.with_index(1) do |travel, index|%>
    <h3><%= "#{index}. " %><%= link_to travel.name, travel_path(travel) %></h3>
  <% end %>

<h2> View offers by category </h2>

<ul>
<li><%=link_to "Food", {:controller => "companies", :action => "category", :category => "food" }%></li>
<li><%=link_to "Technology", {:controller => "companies", :action => "category", :category => "technology" }%></li>
<li><%=link_to "Clothing", {:controller => "companies", :action => "category", :category => "clothing" }%></li>
<li><%=link_to "Footwear", {:controller => "companies", :action => "category", :category => "footwear" }%></li>
<li><%=link_to "Auto", {:controller => "companies", :action => "category", :category => "auto" }%></li>
<li><%=link_to "Drugstore", {:controller => "companies", :action => "category", :category => "drugstore" }%></li>
</ul>

<br><br>
<h3><%= link_to 'View all current offers', offers_path %></h3>

<% if user_signed_in? && admin %>
  <%= link_to "Add a new travel", new_travel_path %>
<% end %>
</div>

app/views/travels/new.html.erb
<h2> Enter a new travel </h2>

<div class=field_with_errors>
  <%= render partial: '/errors', locals: { record: @travel } %>
</div>

<%= form_for @travel do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.submit %>
<% end %>

app/views/travels/show.html.erb
<div class="current-offers">
<h2> All current offers </h2>

<% if user_signed_in? %>
  <%= link_to "Add a new offer for a company on this route", new_travel_offer_path(@travel) %>
  <h3> <%= link_to "View your offers on this route", travel_offers_path(@travel) %> </h3>
<% end %>
  <h3> <%= link_to "View offers on another route", travels_path %> </h3>


<h2><%= @travel.name %></h2>

  <% @travel.companies.each.with_index(1) do |company, index| %>
  <h3><%=index%></h3>
  <h3>Company: <%= company.name %></h3>
  <h3>Category: <%= company.category %></h3>
    <% company.offers.each do |offer| %>
      <p>Description: <%= offer.description %></p>
    <%end%>
  <% end %>
  </div>

app/views/users/new.html.erb
<h2>Create a new user account </h2>

<%= render partial: '/errors', locals: { record: @user } %>

<%= form_for @user, url: signup_path do |f| %>
  <%= f.label :Username %>
  <div><%= f.text_field :username %></div>
  <%= f.label :Password %>
  <div><%= f.password_field :password %></div>
  <%= f.label :Password_Confirmation %>
  <div><%= f.password_field :password_confirmation %></div>
  <%= f.submit %>
<% end %>